### ISSUE TITLE
readme example improvements 

### ISSUE THREAD

**Issue by voidhaze** [go-qbit/template#5]
Tried to follow the example in the README, found a few mistakes / potential improvements

1) in step 3 please include package name declaration (package template) for template/user.go
2) is it unclear where the file in step 4 should live please clarify (./main.go)
3) step 4 has incorrect package call in main.main() ; templates.ProcessTest should be template.ProcessTest and []templates.User should be []template.User
4) missing go build step at the end, missing run step for exec

**Comment by voidhaze** [comment]
On a completely different note, would be nice if we could generate the HTML with out having to generate the templates then compile binary, seems to be too many steps. Would be cool if the interface worked more like "html/template" or "text/template"

**Comment by sergei-svistunov** [comment]
> On a completely different note, would be nice if we could generate the HTML with out having to generate the templates then compile binary, seems to be too many steps. Would be cool if the interface worked more like "html/template" or "text/template"

To be honest I haven't understood what do you mean. Could you please explain or give an example?

**Comment by sergei-svistunov** [comment]
@voidhaze, please check PR  #6. I will merge it if now everything is clear.

**Comment by voidhaze** [comment]
looks good.

**Comment by voidhaze** [comment]
In regards to the interface I found a example here https://golang.org/doc/articles/wiki/#tmp_6
however their example is a bit long. found a shorter example below (http://www.alternatestack.com/development/app-development/simple-http-server-with-templated-response-in-go/):

```
package main

import "fmt"
import "net/http"
import "html/template"

type Student struct {
	Id   int
	Name string //exported field since it begins with a capital letter
}

func indexHTMLTemplateVariableHandler(response http.ResponseWriter, request *http.Request) {
	tmplt := template.New("IndexTemplated.html")       //create a new template with some name
	tmplt, _ = tmplt.ParseFiles("IndexTemplated.html") //parse some content and generate a template, which is an internal representation

	p := Student{Id: 1, Name: "Aisha"} //define an instance with required field

	tmplt.Execute(response, p) //merge template ‘t’ with content of ‘p’
}

func main() {
	fmt.Println("Starting Server for Templated response from file")

	http.HandleFunc("/top-student-from-file", indexHTMLTemplateVariableHandler)

	http.ListenAndServe(":8080", nil)
}
```

**Comment by sergei-svistunov** [comment]
The Go template engine translates files on the fly, that's why it spends more resources. My template engine generates Go code in advance and also Go compiler can optimize it while compiling sources. 
I'm afraid it's impossible to do what you want.

**Comment by voidhaze** [comment]
Thanks for the info, hope the project goes well.
